### PR TITLE
meta-networking/licenses/netperf: remove unused license

### PR DESCRIPTION
**Pull request by ArsalanHAwan**
This removes the old unused license for netperf as upstream moved to using the MIT license for netperf.

See: meta-openembedded commit 587fe5877790b6c2e1d337c351b8f50603ad4db9

### CODE REVIEW

**Comment by kraj** [comment]
applied with 27bdecd1bc

**Comment by ArsalanHAwan** [comment]
@kraj can we please merge this into kirkstone as well?

**Comment by ArsalanHAwan** [comment]
@kraj can we please merge this into kirkstone as well?

**Comment by kraj** [comment]
create a pull request for `kirkstone` here as well if you can.

**Comment by akuster** [comment]
pulled into the next mickledore, langdale & kirkstone

**Pull request closed without merging**
