### PR TITLE
Backport from master

### PR DESCRIPTION
**Pull request by mnsgs**
Fix wrong checksum of devmem2

### CODE REVIEW

**Comment by shr-project** [comment]
We don't do pull-requests as github is only read-only mirror, see:
https://github.com/openembedded/meta-openembedded/blob/master/meta-oe/README#L7

**Comment by gizero** [comment]
So, shouldn't we drop (or at least reword) the README a couple of line below the one you highlight? To me it sounds like we are encouraging to use GitHub, at least for sets of more than one patch...

**Comment by mnsgs** [comment]
Agree, this was exactly what mislead me.

**Comment by shr-project** [comment]
Agreed, it's misleading. Patches to improve it are also welcome on openembedded-devel ML :).

**Pull request closed without merging**
