### PR TITLE
Update UPSTREAM_CHECK_* variables to fix devtool upgrades

### PR DESCRIPTION
**Pull request by ycongal-smile**
Update UPSTREAM_CHECK_* variables to fix UNKNOWN_BROKEN status with devtool check-upgrade-status.

---
This is a preview of the PR with only 17 recipes, the full will have 100.
EDIT: Full list of 95 recipes is ready.

### CODE REVIEW

**Comment by ycongal-smile** [comment]
Hi @kraj, can you tell me if this is the good format for this? (1 commit by recipe, commit message, ...)
I'd rather know we are on good tracks before finishing the whole 100 recipe set...

Thank you!

**Comment by kraj** [comment]
> Hi @kraj, can you tell me if this is the good format for this? (1 commit by recipe, commit message, ...) I'd rather know we are on good tracks before finishing the whole 100 recipe set...
> 
> Thank you!
this looks good start,I think ensuring these being correct is the key. how are you testing it

**Comment by ycongal-smile** [comment]
> this looks good start,I think ensuring these being correct is the key. how are you testing it

We will ensure that `devtool check-upgrade-status -a $recipe` does not return `UNKNOWN_BROKEN`.

This list of recipe (the 100) is a subset of a larger list of fixes we have.
These are the simple ones, every complex cases are on hold for now (we plan to publish them at some point but 1 step at a time)

**Comment by ycongal-smile** [comment]
Full list is now ready!

<details><summary>Tests done : "devtool check-upgrade-status" on every patched recipe </summary>

```
 $ cat test.sh 
#!/bin/sh

LIST="ace acpitool anthy atop bitwise cfengine-masterfiles ckermit cloc cups-filters cxxtest czmq daemontools dbus-broker doxygen duktape fftw fltk fltk-native fwupd gmime gnome-themes-extra gradm graphviz gtkperf hplip icewm irssi jansson lcov leptonica libcdio-paranoia libdbus-c++ libee libftdi libgnt libiodbc libjs-jquery liblinebreak libmng libmtp libnice libopusenc libpaper libpcsc-perl libsdl-gfx libsigc++-2.0 libsigc++-3 libsmi libspiro libstatgrab libwmf libx86-1 libxml++-5.0 logwarn lprng mariadb mariadb-native mbuffer mcpp microcom mozjs-115 mscgen msgpack-cpp msktutil nmon nss obexftp onig openbox openbox-xdgmenu openct openobex p7zip pngcheck proxy-libintl pugixml pv rsyslog sblim-cmpi-devel sblim-sfc-common sblim-sfcc source-code-pro-fonts stalonetray testfloat tk tmux ttf-abyssinica ttf-ubuntu-font-family ttf-wqy-zenhei uim uml-utilities unixodbc xdotool xf86-input-tslib xrdp xscreensaver zeromq"

for r in $LIST; do
	devtool check-upgrade-status -a $r 2>/dev/null |grep "^$r"
done

 $ ./test.sh 
ace                       6.5.19          8.0.0           None  
acpitool                  0.5.1           MATCH           None  
anthy                     9100h           MATCH           None  
atop                      2.4.0           2.10.0          None  
bitwise                   0.50            MATCH           None  
cfengine-masterfiles      3.21.0          3.21.5          None  
ckermit                   302             MATCH           None  
cloc                      1.98            2.00            None  
cups-filters              2.0.0           MATCH           None  
cxxtest                   4.4             MATCH           None  
czmq                      4.2.1           MATCH           None  
daemontools               0.76            MATCH           None  
dbus-broker               36              MATCH           None  
doxygen                   1.9.3           1.11.0          None  
duktape                   2.7.0           MATCH           None  
fftw                      3.3.10          MATCH           None  
fltk                      1.3.8           1.3.9           None  
fltk-native               1.3.8           1.3.9           None  
fwupd                     1.9.18          1.9.21          None  
gmime                     3.2.13          3.2.15          None  
gnome-themes-extra        3.28            MATCH           None  
gradm                     3.1-202111052217 MATCH           None  
graphviz                  8.1.0           12.0.0          None  
gtkperf                   0.40            MATCH           None  
hplip                     3.22.10         3.24.4          None  
icewm                     3.4.5           3.6.0           None  
irssi                     1.4.5           MATCH           None  
jansson                   2.14            MATCH           None  
lcov                      1.16            2.1             None  
leptonica                 1.82.0          1.84.1          None  
libcdio-paranoia          10.2+2.0.1      10.2+2.0.2      None  
libdbus-c++               0.9.0           MATCH           None  
libftdi                   1.5             MATCH           None  
libgnt                    2.14.1          2.14.4          None  
libiodbc                  3.52.15         3.52.16         None  
libjs-jquery              3.3.1           MATCH           None  
liblinebreak              1.2             2.1             None  
libmng                    2.0.3           MATCH           None  
libmtp                    1.1.21          MATCH           None  
libnice                   0.1.22          MATCH           None  
libopusenc                0.2.1           MATCH           None  
libpaper                  2.1.2           2.2.5           None  
libpcsc-perl              1.4.14          1.4.15          None  
libsdl-gfx                2.0.25          2.0.27          None  
libsigc++-2.0             2.12.1          MATCH           None  
libsigc++-3               3.6.0           MATCH           None  
libsmi                    0.5.0           MATCH           None  
libspiro                  20221101        MATCH           None  
libstatgrab               0.92.1          MATCH           None  
libwmf                    0.2.8.4         MATCH           None  
libx86-1                  1.1             MATCH           None  
libxml++-5.0              5.0.1           5.2.0           None  
logwarn                   1.0.14          1.0.17          None  
lprng                     3.8.C           3.9.0           None  
mariadb                   10.11.7         11.5.1          None  
mariadb-native            10.11.7         11.5.1          None  
mbuffer                   20140310        20240707        None  
mcpp                      2.7.2           MATCH           None  
microcom                  2023.09.0       MATCH           None  
mozjs-115                 115.11.0        115.13.0        None  
mscgen                    0.20            MATCH           None  
msgpack-cpp               6.1.0           6.1.1           None  
msktutil                  1.2.1           MATCH           None  
nmon                      16m             16q             None  
nss                       3.101           3.102           None  
obexftp                   0.24.2          MATCH           None  
onig                      6.9.9           MATCH           None  
openbox                   3.6.1           MATCH           None  
openbox-xdgmenu           0.3             MATCH           None  
openct                    0.6.20          MATCH           None  
openobex                  1.7.2           MATCH           None  
p7zip                     16.02           MATCH           None  
pngcheck                  2.3.0           3.0.3           None  
proxy-libintl             20100902        MATCH           None  
pugixml                   1.14            MATCH           None  
pv                        1.6.20          1.8.12          None  
rsyslog                   8.2404.0        8.2406.0        None  
sblim-cmpi-devel          2.0.3           MATCH           None  
sblim-sfc-common          1.0.1           MATCH           None  
sblim-sfcc                2.2.8           MATCH           None  
source-code-pro-fonts     2.030           2.042           None  
stalonetray               0.8.3           0.8.5           None  
testfloat                 3e              MATCH           None  
tk                        8.6.10          8.6.14          None  
tmux                      3.3a            3.4             None  
ttf-abyssinica            2.100           2.201           None  
ttf-ubuntu-font-family    0.83            MATCH           None  
ttf-wqy-zenhei            0.9.45          MATCH           None  
uim                       1.8.9           MATCH           None  
uml-utilities             20040406        MATCH           None  
unixodbc                  2.3.12          MATCH           None  
xdotool                   3.20211022.1    MATCH           None  
xf86-input-tslib          1.1.1           MATCH           None  
xrdp                      0.9.19          0.10.0          None  
xscreensaver              6.04            6.09            None  
zeromq                    4.3.5           MATCH           None  
```


</details>

**Comment by ycongal-smile** [comment]
Merged in b2bfb9efca -> 5b33cbfe99 : `git log b2bfb9efca^..5b33cbfe99`
Thanks @kraj !

**Pull request closed without merging**
