### PR TITLE
exprtk: upgrade 0.0.2 -> 0.0.3 release

### PR DESCRIPTION
**Pull request by ArashPartow**
1. Improved and additional run-time checks:
   * Assert statement
   * Vector access checks
   * stack depth checks
   * Significantly reduced latencies when RTCs are enabled

2. Addition of resizable vector type

3. Significantly improved expression evaluation time
   * Additional optimisation passes for three and four inter-scalar operations

4. Compilation time performance improvements

5. Additional stack protections when using function compositions

6. Improved precision for erf/erfc/asinh/acosh functions

7. Update to build with the following compilers:
   * g++14
   * clang++ v20

### CODE REVIEW

**Comment by kraj** [comment]
fails to fetch 

```
stdio: ERROR: exprtk-git-r0 do_fetch: Fetcher failure: Unable to find revision dd7b1ff4ad66572e09078a49eaf5bfec5adeaedb in branch release even from upstream
stdio: ERROR: exprtk-git-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/ArashPartow/exprtk.git;branch=release;protocol=https')
```

detailed log
https://valkyrie.yoctoproject.org/#/builders/81/builds/132/steps/14/logs/stdio

**Comment by ArashPartow** [comment]
@kraj: I've fixed the commit hash and updated to commit message. 

Not sure, but I think the pipeline was rerun [here](https://valkyrie.yoctoproject.org/#/builders/81/builds/138) but it still seems to be failing on something not related to this PR. Can you rerun the pipeline.

**Comment by kraj** [comment]
applied with a90a83ed1c

**Comment by ArashPartow** [comment]
thanks 👍

**Pull request closed without merging**
