### PR TITLE
libp11: upgrade 0.4.12 -> 0.4.13

### PR DESCRIPTION
**Pull request by embetrix**
libp11: upgrade 0.4.12 -> 0.4.13

### CODE REVIEW

**Review by kraj — CHANGES_REQUESTED** [review]
please add your sign-off-by to the patch

**Comment by kraj** [comment]
it fails to apply a patch, how did you test it ? see
https://valkyrie.yoctoproject.org/#/builders/81/builds/212/steps/14/logs/stdio

**Comment by embetrix** [comment]
@kraj: the patch is already applied upstream so I removed it, sorry for the confusion.

**Comment by kraj** [comment]
I have taken a similar patch which was submitted to ML separately.

**Pull request closed without merging**
