### PR TITLE
cockpit: upgrade 218 -> 219

### PR DESCRIPTION
**Pull request by hoinmic**
Update cockpit to version 219

### CODE REVIEW

**Comment by kraj** [comment]
always add a sign-off to pulls e.g.
https://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines#Patch_Headers_and_Commit_Messages

**Comment by hoinmic** [comment]
@kraj Yes. oh sorry.

**Comment by hoinmic** [comment]
@kraj The commit message is now signed.

**Comment by kraj** [comment]
merged with ba6fbd90c7

**Pull request closed without merging**
