### PR TITLE
libqmi: Upgrade 1.32.4 -> 1.34.0

### PR DESCRIPTION
**Pull request by capiman**
Changelog:
https://gitlab.freedesktop.org/mobile-broadband/libqmi/-/blob/1.34.0/NEWS

### CODE REVIEW

**Comment by capiman** [comment]
@Qingwu-Li I assume your commit was referring my change by fault, because mine has nothing to do with tcpreplay...?

**Comment by Qingwu-Li** [comment]
> @Qingwu-Li I assume your commit was referring my change by fault, because mine has nothing to do with tcpreplay...?

It seems that a automatic referring，no idea why，my change does not depend on yours neither

**Comment by shr-project** [comment]
> > @Qingwu-Li I assume your commit was referring my change by fault, because mine has nothing to do with tcpreplay...?
> 
> It seems that a automatic referring，no idea why，my change does not depend on yours neither

github is just too eager to assume that every '#749' in commit message has to mean reference to pull request in the repo (if it exists). See the original commit in patchwork:

https://patchwork.yoctoproject.org/project/oe/patch/20230628095548.1062348-1-archana.polampalli@windriver.com/

**Comment by capiman** [comment]
Just saw, it was already merged (via patch on mailing list). So this merge request is no longer needed and can be closed.

**Pull request closed without merging**
