### PR TITLE
Backport of fixes to dunfell

### PR DESCRIPTION
**Pull request by diegorondini**
Backport of bugfixes from master to dunfell. In particular:

- fix broken fuse dependency in gvfs
- fix eigen fetch URL
- fix hplip backend and filter folders

### CODE REVIEW

**Comment by kraj** [comment]
@akuster in your court.

**Comment by diegorondini** [comment]
Ping

**Comment by akuster** [comment]
Ill look at it this weekend.

**Comment by diegorondini** [comment]
Ping again.

**Comment by kraj** [comment]
@diegorondini if possible please send this series to oe-devel mailing list too

**Comment by akuster** [comment]
these are staged in stable/dunfell-nut

**Comment by kraj** [comment]
applied with 
8d0ef1e05cb595f2bdccccaeab0e182e67b7a366
4cc265d4de8c17a916dcf4dfd31666ad97881763
d89968b63f16f49ff04f37dbfb55fb078f5f2541
636daeba35c5b9ec8e570225353a78c591c98756

**Pull request closed without merging**
