### PR TITLE
[gatesgarth-next] Add libpapi.5.7.0

### PR DESCRIPTION
**Pull request by nonifier**
Add papi 5.7.0 support to Gatesgarth

Signed-off-by: Olivier Georget <olivier.georget@gmail.com>

### CODE REVIEW

**Comment by kraj** [comment]
cherry-picked for master-next

**Comment by kraj** [comment]
this fails to build on many combinations e.g. mips/glibc

https://errors.yoctoproject.org/Errors/Details/586891/

same errors seen on riscv32/riscv64/musl/x86

**Review by kraj — CHANGES_REQUESTED** [review]
We have a matrix of architectures where its failing so please take a look and resubmit.

https://errors.yoctoproject.org/Errors/Details/586880/

**Comment by kraj** [comment]
here is list of failures

https://errors.yoctoproject.org/Errors/Search/?query=papi&filter=%20papi:%20do_compile&type=failure

**Comment by akuster** [comment]
This is fine for master but adding a new package to a stable branch is not allowed.

**Comment by nonifier** [comment]
Thanks for the feedback @kraj, I'll have a look.
Do you have any suggestion on how to quickly test on different architectures ? I'm currently only building/testing on an arm64 🤔

**Comment by kraj** [comment]
> Thanks for the feedback @kraj, I'll have a look.
> Do you have any suggestion on how to quickly test on different architectures ? I'm currently only building/testing on an arm64 🤔

```
MACHINE=qemumips TCLIBC=musl bitbake libpapi
```

**Comment by kraj** [comment]
@akuster as `gatersgarth` is EOL, should this be closed as `wont-fix`

**Pull request closed without merging**
