### PR TITLE
lvgl: Add dialog-lvgl recipe as demo example

### PR DESCRIPTION
**Pull request by rzr**
This example was written just to validate lvgl on wayland,
Feel free to get inspiration from.

Origin: https://github.com/astrolabe-coop/meta-openembedded
Forwarded: https://github.com/openembedded/meta-openembedded/pulls?q=author%3Arzr
Signed-off-by: Philippe Coval <philippe.coval.ext@huawei.com>

### CODE REVIEW

**Comment by rzr** [comment]
Applied 8d75eff6af0fd6ccf8a45b5c98c4a0194e292a2f


http://cgit.openembedded.org/meta-openembedded/commit/meta-oe/recipes-graphics/lvgl?id=8d75eff6af0fd6ccf8a45b5c98c4a0194e292a2f

Feel free to close

**Comment by stacktrust** [comment]
@rzr @kraj 

Original repo seems to be offline: https://git.ostc-eu.org/rzr/dialog-lvgl/

Should we update the recipe with this source? https://gitlab.eclipse.org/pcoval/dialog-lvgl

**Comment by kraj** [comment]
Yes if you can send a patch that would be awesome

**Comment by rzr** [comment]
hi I am the one behind this project, I could host it on github if it helps

**Comment by kraj** [comment]
> hi I am the one behind this project, I could host it on github if it helps

github works too, however, I hope it is well maintained and in good health, wherever it resides is
immaterial.

**Comment by stacktrust** [comment]
> hi I am the one behind this project, I could host it on github if it helps

That would make the source repo easier to locate. Github issues could be used for reporting any build issues with OE or LVGL.

This project may be undersold as LVGL example/demo. E.g. we have a small OE Linux and Xen installer (https://github.com/openxt/installer) that uses ncurses dialog, which could potentially use dialog-lvgl for Linux framebuffer graphics on x86 and Arm. Compatible dialog features could be added to this project as needed by downstream user scripts, since dialog-lvgl is a small codebase with minimal dependencies.

If you could test/uprev the code and OE recipe for LVGL 8.3 (per the removal report) and 9.x (current OE master), that should address the reasons for the recipe being removed from OE. If you would welcome contributions to improve compatibility with other dialog implementations, perhaps mention that in the README? Also include your preferred contact channel as project maintainer, in the OE recipe and/or project README.

Thanks for creating this simple but powerful demo of OE+LVGL. With more users and contributors, it could become broadly useful in both embedded and non-embedded contexts, when small footprint and graphics performance are needed.

**Comment by rzr** [comment]
Feel free to jump to:

https://github.com/rzr/dialog-lvgl

I can review patches

**Pull request closed without merging**
