### PR TITLE
pahole: call python via env in the shebang

### PR DESCRIPTION
**Pull request by teknoraver**
Signed-off-by: Matteo Croce <mcroce@microsoft.com>

### CODE REVIEW

**Comment by kraj** [comment]
another signature mismatch issue see here

http://jenkins.nas-admin.org/view/OE/job/oe_world_workspace-compare-signatures/1062/console

**Comment by teknoraver** [comment]
I don't have this error locally.
I don't really know what's causing it. Any hint?

**Comment by kraj** [comment]
> I don't have this error locally.
> I don't really know what's causing it. Any hint?

you can add a temp machine conf e.g. see
https://github.com/YoeDistro/openembedded-core/commit/67298dd2359229154de294e7b83b23f5df12b251

then build pahole for this machine again 

then do 

bitbake-diffsig on it.

**Comment by kraj** [comment]
merged with b23770aa9f

**Comment by shr-project** [comment]
> I don't have this error locally. I don't really know what's causing it. Any hint?

```
oe-core$ openembedded-core/scripts/sstate-diff-machines.sh --tmpdir=tmp-glibc --machines="qemux86 qemux86copy qemuarm" --targets=pahole --analyze
```

shows:
```
 === Comparing signatures for task do_configure.sigdata between qemux86 and qemux86copy ===
ERROR: pahole different signature for task do_configure.sigdata between qemux86 and qemux86copy
NOTE: Reconnecting to bitbake server...
Hash for dependent task pahole/pahole_1.22.bb:do_prepare_recipe_sysroot changed from bfa7a0e0c59d99b0133ab295ebf7025a430242d4b8874d436d47cf8157192999 to e45ada248cd757d742872183d9fe426a7ce3b44a652b0900709ad3d0f3f64aa8
Unable to find matching sigdata for /OE/build/oe-core/meta-openembedded/meta-oe/recipes-devtools/pahole/pahole_1.22.bb:do_prepare_recipe_sysroot with hashes bfa7a0e0c59d99b0133ab295ebf7025a430242d4b8874d436d47cf8157192999 or e45ada248cd757d742872183d9fe426a7ce3b44a652b0900709ad3d0f3f64aa8

ERROR: 1 errors found in /OE/build/oe-core/tmp-glibc/sstate-diff/1633081392/signatures.qemux86copy.do_configure.sigdata.log
```

and
```
oe-core$ bitbake-diffsigs tmp-glibc/sstate-diff/1633081392/qemux86*/core2-32-oe-linux/pahole/*prepare_recipe_sysroot*
NOTE: Starting bitbake server...
NOTE: Started PRServer with DBfile: /OE/build/oe-core/cache/prserv.sqlite3, Address: 127.0.0.1:38435, PID: 21321
Hash for dependent task libbpf/libbpf_0.5.bb:do_populate_sysroot changed from 95bfd90e188d9ee6b4797736b07339d616655173a58a3f4f4f2ab4a5fa0bf3d8 to 9556bc318991640bba0eacc8f2102167bc7c389c13dadf08d69a9b864feae5c9
Unable to find matching sigdata for /OE/build/oe-core/meta-openembedded/meta-oe/recipes-kernel/libbpf/libbpf_0.5.bb:do_populate_sysroot with hashes 95bfd90e188d9ee6b4797736b07339d616655173a58a3f4f4f2ab4a5fa0bf3d8 or 9556bc318991640bba0eacc8f2102167bc7c389c13dadf08d69a9b864feae5c9
```

meta-openembedded/meta-oe/recipes-kernel/libbpf/libbpf_0.5.bb is MACHINE_ARCH, so pahole needs to be MACHINE_ARCH as well when it depends on it. Will send a fix for this.

**Pull request closed without merging**
