### PR TITLE
pim435: Add recipe for C implementation for userspace driver app

### PR DESCRIPTION
**Pull request by rzr**
Origin: https://booting.oniroproject.org/distro/oniro/-/merge_requests/402
Forwarded: https://github.com/openembedded/meta-openembedded/pulls?q=rzr
Relate-to: https://git.ostc-eu.org/distro/components/vending-machine-control-application/-/issues/2
Relate-to: https://booting.oniroproject.org/distro/oniro/-/merge_requests/416
Thanks-to: Andrei Gherzan's avatarAndrei Gherzan <andrei.gherzan@huawei.com>
Signed-off-by: Philippe Coval <philippe.coval@huawei.com>

### CODE REVIEW

**Comment by kraj** [comment]
fails to build with clang see 
https://errors.yoctoproject.org/Errors/Details/618058/

**Comment by rzr** [comment]
need this patch, I'll fix it in update patch once released

**Comment by kraj** [comment]
> needs this patch: https://booting.oniroproject.org/distro/components/pim435/-/merge_requests/3
> 
> I'll fix it in update patch once released

OK. Please update this pull request with the fix once ready, I will hold on to this pull until then

**Review by kraj — CHANGES_REQUESTED** [review]
please include the fix to build with clang.

**Comment by kraj** [comment]
applied with 9f9bb90be0

**Pull request closed without merging**
