### PR TITLE
zchunk: add recipe

### PR DESCRIPTION
**Pull request by texierp**
zchunk is a compressed file format that splits the file into independent chunks.
This allows you to only download changed chunks when downloading a new version of
the file, and also makes zchunk files efficient over rsync.

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>

### CODE REVIEW

**Comment by kraj** [comment]
fail on musl
https://errors.yoctoproject.org/Errors/Details/307962/

**Comment by texierp** [comment]
Thanks @kraj, I will fix that

**Comment by texierp** [comment]
@kraj PR updated, tested with `TCLIBC = "musl"`.

**Comment by kraj** [comment]
in master-next now

**Comment by texierp** [comment]
Merged in master https://github.com/openembedded/meta-openembedded/commit/5c453ae57830b379355a3bddb4bd9d556584d411

**Pull request closed without merging**
