### PR TITLE
bdwgc: upgrade 7.6.12 -> 8.0.4

### PR DESCRIPTION
**Pull request by ivmai**
Highlights of this upgrade:
* Add initial RISC-V support
* Enable handle-fork and memory unmapping by default
* New API to turn on manual VDB at runtime
* Turn on parallel marker by default for all multi-threaded builds
* Use thread-local allocations for all multi-threaded builds

See the following for detailed changes:
* https://github.com/ivmai/bdwgc/releases/tag/v8.0.0
* https://github.com/ivmai/bdwgc/releases/tag/v8.0.2
* https://github.com/ivmai/bdwgc/releases/tag/v8.0.4

Signed-off-by: Ivan Maidanski <ivmai@mail.ru>

### CODE REVIEW

**Comment by ivmai** [comment]
LIC_FILE_CHECKSUM has changed because the md5 is calculated of README file which contains not only license information but also quick notes about the usage and further documentation (e.g. doc/gcinterface.html was renamed to doc/gcinterface.md).

**Comment by ivmai** [comment]
Is the commit message update is needed?

**Comment by kraj** [comment]
yes update is needed.

**Comment by ivmai** [comment]
> yes update is needed.

Done.

**Comment by ivmai** [comment]
Hello @kraj, I've added the following to the commit message:

`The LIC_FILES_CHKSUM has changed because the file (README.QUICK)
contains not only the license information but also some quick tips
about the library build, the latter has been updated a bit.`

**Comment by kraj** [comment]
This has been merged 0a1c33dde337084a8d691163454bf2e344550aca

**Pull request closed without merging**
