### PR TITLE
python3-jdatetime: Added recipe

### PR DESCRIPTION
**Pull request by colin-pm**
Created python3 recipe for jdatetime.

Signed-off-by: Colin McAllister <colinmca242@gmail.com>

### CODE REVIEW

**Comment by kraj** [comment]
fails to build

**Comment by colin-pm** [comment]
My apologies, this recipe was pointed to an older version and I bumped it before creating the PR.  Looks like the license file was removed, but the setup.py file and PKG-INFO file still reference a python-2.0 license.  I switched LICENSE to point to PKG-INFO.

**Comment by kraj** [comment]
> My apologies, this recipe was pointed to an older version and I bumped it before creating the PR. Looks like the license file was removed, but the setup.py file and PKG-INFO file still reference a python-2.0 license. I switched LICENSE to point to PKG-INFO.

thanks for update, I still need you to update the pull, and preferably make one pull for set of changes, there is no need to have one pull per recipe, one commit per recipe is ok though.

**Comment by kraj** [comment]
merged to master c45c5fff8d

**Pull request closed without merging**
