### PR TITLE
Add Toybox Inittab

### PR DESCRIPTION
**Pull request by miartad**
Add toybox inittab recipe with lightweight files to make init from toybox possible.

When user selects toybox as init manager toybox get rdependency on toybox-inittab.

The PACKAGECONFIG getty feature is for my specific use case so I have left it as a separate commit, you may want to reject.

### CODE REVIEW

**Comment by kraj** [comment]
Can you rebase it against master

**Comment by miartad** [comment]
rebased

**Comment by miartad** [comment]
I just realized this needs additional commit to add:

conf/distro/include/init-manager-toybox.inc

this should use VIRTUAL-RUNTIME_initscripts which will create rc*d directories, so it will not be necessary for toybox to do, I will do the rework soon

**Comment by kraj** [comment]
I  am seeing errors like 
```
ERROR: Logfile of failure stored in: /home/pokybuild/yocto-worker/meta-oe/build/build/tmp/work/qemux86_64-poky-linux/toybox-inittab/0.8.2-r0/temp/log.do_configure.1229174
Log data follows:
| DEBUG: Executing shell function do_configure
| /home/pokybuild/yocto-worker/meta-oe/build/build/tmp/work/qemux86_64-poky-linux/toybox-inittab/0.8.2-r0/temp/run.do_configure.1229174: 105: Bad substitution
| WARNING: exit code 2 from a shell command.
| ERROR: Execution of '/home/pokybuild/yocto-worker/meta-oe/build/build/tmp/work/qemux86_64-poky-linux/toybox-inittab/0.8.2-r0/temp/run.do_configure.1229174' failed with exit code 2:
| /home/pokybuild/yocto-worker/meta-oe/build/build/tmp/work/qemux86_64-poky-linux/toybox-inittab/0.8.2-r0/temp/run.do_configure.1229174: 105: Bad substitution
| WARNING: exit code 2 from a shell command.
| 

```

I wonder if its related to shell

**Comment by shr-project** [comment]
Yes, I'm seeing the same when dash is being used instead of proper bash. Can we please revert if from master until the original submitter updates this PR?

**Comment by miartad** [comment]
${file/file:\/\//} expansion not supported in dash, I will find a workaround

**Comment by kraj** [comment]
> Yes, I'm seeing the same when dash is being used instead of proper bash. Can we please revert if from master until the original submitter updates this PR?

yeah I was holding on to it. but then ended up accepting it. I would like a fix instead of a revert if possible. @miartad are you working on fixing this?

**Comment by shr-project** [comment]
Thanks for sending fix to ML.

I was asking for revert, because there wasn't any feedback on your review for 9 days and I didn't want to force you to fix it yourself :). But this is of course better. Thanks!

**Comment by miartad** [comment]
@kraj I think your fix is fine.

with regards to changes I wanted to make - provide "init-manager-toybox.inc" - this functionality exists in poky, so for this PR there is nothing more to do for me, unless you have additional comments

**Comment by kraj** [comment]
its merged

**Pull request closed without merging**
