### PR TITLE
ser2net/gensio

### PR DESCRIPTION
**Pull request by texierp**

### CODE REVIEW

**Comment by kraj** [comment]
gensio fails to configure 

http://errors.yoctoproject.org/Errors/Details/392877/

**Comment by texierp** [comment]
> gensio fails to configure
> 
> http://errors.yoctoproject.org/Errors/Details/392877/

Thanks @kraj , I will check that

**Comment by texierp** [comment]
@kraj, PR updated, it seems the problem comes from openssl if libssl is already installed on the Host machine.

Should be fine now.

**Comment by kraj** [comment]
they are in master now

**Pull request closed without merging**
