### PR TITLE
[meta-oe] recipes-kernel: add libbpf

### PR DESCRIPTION
**Pull request by teknoraver**
Add a recipe to build libbpf from https://github.com/libbpf/libbpf

Signed-off-by: Matteo Croce <mcroce@microsoft.com>

### CODE REVIEW

**Comment by akuster** [comment]
I thought this was already sent to core mailing list.

**Comment by teknoraver** [comment]
@akuster yes, but to the wrong layer. I moved it into meta-oe.

**Comment by kraj** [comment]
https://errors.yoctoproject.org/Errors/Details/571937/

**Comment by teknoraver** [comment]
Hi @kraj

I found a typo in my recipe (`LICENSE.LGPL-2.1` was incorrectly named `LICENSE.LPGL-2.1`) so I fixed it.
Fun fact, the file name was wrong in the upstream repo, so I created a PR for that: https://github.com/libbpf/libbpf/pull/241

**Comment by kraj** [comment]
hash mismatches
http://jenkins.nas-admin.org/view/OE/job/oe_world_workspace-compare-signatures/1017/console

**Comment by kraj** [comment]
another instance http://jenkins.nas-admin.org/view/OE/job/oe_world_workspace-compare-signatures/1018/console
I am dropping this from master-next

**Review by kraj — CHANGES_REQUESTED** [review]
this is still failing sstate signature check http://jenkins.nas-admin.org/view/OE/job/oe_world_workspace-compare-signatures/1018/console

**Comment by teknoraver** [comment]
@kraj the problem was that the recipe was dependent to the kernel config.

I've pushed a fix

**Review by kraj — COMMENTED** [review]
thanks I have staged it for master-next lets see if it stands the tests this time.

**Comment by kraj** [comment]
its in master with e80d14dc55f909a60d4bee810c0b9b0377bbf59e

**Comment by teknoraver** [comment]
Great!
Now I'll push the changes to bcc and bpftrace to use it.

**Pull request closed without merging**
