### PR TITLE
Add python-cryptography to RDEPENDS for python-redis

### PR DESCRIPTION
**Pull request by Bog999**

### CODE REVIEW

**Comment by kraj** [comment]
Can you rebase it on latest master-next please ?

**Comment by kraj** [comment]
if this is just for zeus then let @akuster know

**Comment by Bog999** [comment]
I need the patch on zeus. I can create one for master-next too, but the recipes there are a little different and also I won't be able to test it. Is this acceptable?

**Comment by kraj** [comment]
Yes that’s ok if rdep is needed then it’s making things better

**Comment by akuster** [comment]
need this in dunfell first. backporting now

**Comment by kraj** [comment]
@akuster zeus has reached EOL and is in community support, if you do not plan to apply this patch to zeus, then make that resolution and close this PR. Its already in master and dunfell 2d964c9051632eb4d1896a4ef4d5eb2203f79570

**Comment by kraj** [comment]
this is now fixed in master and dunfell which are maintained releases

**Pull request closed without merging**
