### PR TITLE
[master] Fix unreachable SRC_URIs referring to the Debian pool

### PR DESCRIPTION
**Pull request by rohieb**
Originally I just wanted to fix up openct, which is no longer available in the Debian pool, but the other two were also discovered while trying to fix it.

### CODE REVIEW

**Comment by rohieb** [comment]
Mmmh, the openct tarballs from github are apparently different from the other ones, and the patches no longer apply… This needs some more work.

**Comment by rohieb** [comment]
Alright, works for me now.

**Comment by kraj** [comment]
this is now merged into master

**Comment by rohieb** [comment]
@akuster At least the first commit (openct) is also an issue on dunfell. Do you want a separate PR, or can you cherry-pick?

**Pull request closed without merging**
