### PR TITLE
ExprTk: Update package to release/0.0.2

### PR DESCRIPTION
**Pull request by ArashPartow**
Updates include:

1. Runtime checks to expression
2. Stackoverflow protections during compilation and expression evaluation
3. Various evaluation performance improvements

### CODE REVIEW

**Comment by ArashPartow** [comment]
@kraj  when you have a moment can you please review and merge this PR

**Review by kraj — COMMENTED** [review]
Thanks for your patch. It looks ok, except that patch subject should follow the commit guidelines [1], see section `Patch Headers and Commit Messages`

[1] https://www.openembedded.org/wiki/Commit_Patch_Message_Guidelines

**Comment by ArashPartow** [comment]
@kraj  I've updated the commit message and added some notes

**Comment by geissonator** [comment]
Ahh, we just hit this over in openbmc. Did we lost the previous commit (force push into master?) We can't build the previous recipe anymore.

**Comment by shr-project** [comment]
Looks like the commit really disappeared :( force pushing to publicly consumed branch is bad practice (I do it all the time for my personal branches, but nobody should be using them from upstream).

```
martin@jama /OE/exprtk $ git branch -a --contains 281c2ccc65b8f91c012ea3725ebcef406378a225
error: no such commit 281c2ccc65b8f91c012ea3725ebcef406378a225

martin@jama /OE/exprtk $ git branch -a --contains f46bffcd6966d38a09023fb37ba9335214c9b959
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/origin/release
```

**Comment by kraj** [comment]
I usually cherry-pick from github PRs into `master-next` for CI purpose, so its there on master-next https://git.openembedded.org/meta-openembedded/log/?h=master-next

Can you check if its still the same ?

**Comment by geissonator** [comment]
Fix over in master-next at https://git.openembedded.org/meta-openembedded/commit/?h=master-next&id=98323c08a76cf54d0dd6a0c279c3c3e14494c04a looks good to me. Thanks!

**Comment by ArashPartow** [comment]
Apologies all for the confusion. The release branch is intended to be clean and will not have force pushes done on it.   I also agree with @shr-project that snapshots are a good idea for reproducible build use-cases.

**Comment by kraj** [comment]
This is now in master - 0522e66a26

**Pull request closed without merging**
