### PR TITLE
bdwgc: upgrade 7.6.8 -> 7.6.10

### PR DESCRIPTION
**Pull request by ivmai**
Highlights of this upgrade:
* Fix races, deadlocks, bugs in disclaim finalization and find-leak mode

See the following for detailed changes:
* https://github.com/ivmai/bdwgc/releases/tag/v7.6.10

Signed-off-by: Ivan Maidanski <ivmai@mail.ru>

### CODE REVIEW

**Comment by ivmai** [comment]
\+ @kraj

**Comment by kraj** [comment]
its staged, we do not merge gh pulls. But instead patches from mailing lists get into master-next and then eventually into master, I will cherry pick this into next for testing.

**Comment by ivmai** [comment]
> its staged, we do not merge gh pulls. But instead patches from mailing lists ...
Yes, I understand, thank you, it is the simplest way for me.

**Comment by kraj** [comment]
merged

**Pull request closed without merging**
