### PR TITLE
Backport uutils-coreutils 0.0.27 to scarthgap

### PR DESCRIPTION
**Pull request by Ecordonnier**
uutils-coreutils 0.0.26 and 0.0.27 contain many bugs-fixes which would be useful on scarthgap.

### CODE REVIEW

**Comment by Ecordonnier** [comment]
Sorry, I think I missed a build issue. I'll need to rework this.

**Comment by Ecordonnier** [comment]
@kraj should I rather use the mailing-list? I see that @akuster has had backport github PRs assigned for months without activity, e.g. https://github.com/openembedded/meta-openembedded/pull/795

**Comment by kraj** [comment]
> @kraj should I rather use the mailing-list? I see that @akuster has had backport github PRs assigned for months without activity, e.g. #795

Yeah that will be fine

**Comment by Ecordonnier** [comment]
OK, I posted the patches as https://lists.openembedded.org/g/openembedded-devel/message/111460 and https://lists.openembedded.org/g/openembedded-devel/message/111461

**Comment by Ecordonnier** [comment]
Merged as https://github.com/openembedded/meta-openembedded/commit/8685de2a32e983f196860d767ffd482baf71e30e and https://github.com/openembedded/meta-openembedded/commit/148aedcc043854af31a04bec202928eb4c822ec6

**Pull request closed without merging**
