### PR TITLE
Update wireshark to 2.4.9 on sumo

### PR DESCRIPTION
**Pull request by stfl**

### CODE REVIEW

**Comment by kraj** [comment]
can you post this too oe mailing list please

**Comment by kraj** [comment]
@akuster can you take a look

**Comment by kraj** [comment]
we usually do not do package upgrades in release branches. but I will let @akuster decice that

**Comment by stfl** [comment]
this actually makes sense but then the source package for 2.4.8 needs to be available somewhere.

**Comment by kraj** [comment]
usually we do have source pre-mirror `sources.openembedded.org` but this given release is missing there. may be somone can point to this tarball and we can upload it

**Comment by akuster** [comment]
Wireshark does bug fix only updates on the minor versions.

I just need to figure out how to get the patch

**Comment by akuster** [comment]
2.4 is now up to 2.4.16

**Comment by kraj** [comment]
You can download the patch in raw format just append .patch or .diff to the patch url and you can wget it and use git am

**Comment by akuster** [comment]
I ended up git fetch the branch and cherry-pick from FETCH_HEAD.

**Comment by akuster** [comment]
I merged it to sumo-next in mete-networking.

**Comment by kraj** [comment]
@akuster since its for sumo and sumo is EOL can we close is WONTFIX unless you have other plans.

**Comment by kraj** [comment]
Closing, as we wont apply this for sumo

**Pull request closed without merging**
