### PR TITLE
PHP: fix PACKAGECONFIG usage for soap and zip extensions

### PR DESCRIPTION
**Pull request by meinemitternacht**
PHP 7.4 includes changes to the configure script which cause build
errors when using the zip or soap extensions.

ERROR: php-native-7.4.4-r0 do_configure: QA Issue: php-native: configure was passed unrecognised options: --enable-libxml [unknown-configure-option]
ERROR: php-native-7.4.4-r0 do_configure: Fatal QA errors found, failing task.
ERROR: php-7.4.4-r0 do_configure: QA Issue: php: configure was passed unrecognised options: --with-libzip [unknown-configure-option]
ERROR: php-7.4.4-r0 do_configure: Fatal QA errors found, failing task.

### CODE REVIEW

**Comment by meinemitternacht** [comment]
I just noticed there were some fixes posted to the mailing list that are related to this problem.  I think the SOAP extension issues were not resolved in those.

**Comment by meinemitternacht** [comment]
Hmm.  I'm not sure what happened with the rebase.  I'll try fixing that.

**Comment by meinemitternacht** [comment]
I don't normally use GitHub pull requests, my apologies.  Should be good to go now.

**Comment by kraj** [comment]
merged with 7aeef522ff

**Pull request closed without merging**
