### PR TITLE
libiio: fix build when python bindings are enabled

### PR DESCRIPTION
**Pull request by S4mw1s3**
See https://github.com/openembedded/meta-openembedded/issues/248

Signed-off-by: Sam Van Den Berge <sam.van.den.berge@telenet.be>

### CODE REVIEW

**Comment by S4mw1s3** [comment]
I'm not sure if adding libiio-python3 to IMAGE_INSTALL will actually build the python bindings.
As I understand you need to add libiio-python3 to the libiio PACKAGECONFIG to enable building the python bindings. Then you can add libiio-python3 to IMAGE_INSTALL to also make sure the bindings get installed in the image.

We have a libiio_%.bbappend file where we set the PACKAGECONFIG. Can you perhaps also try that?

**Review by kraj — APPROVED** [review]
lgtm

**Comment by kraj** [comment]
its merged in master with 51f98865da

**Comment by mnsgs** [comment]
Thanks @S4mw1s3 , that does the trick

**Pull request closed without merging**
