### PR TITLE
[dunfell] wireguard: Upgrade to 1.0.20220627 (module) and 1.0.20210914 (tools)

### PR DESCRIPTION
**Pull request by ColinFinck**
Quoting Jason A. Donenfeld on IRC:

```
<zx2c4> Colin_Finck: you should never, ever use old versions
<zx2c4> Notice that neither the major nor minor version numbers change
<zx2c4> Use the latest versions on your LTS
```

With that definite answer, I'd like to fix the problem described in https://lore.kernel.org/yocto/CswA.1659543156268567471.pbrp@lists.yoctoproject.org/ by importing the latest versions instead of maintaining our own fork of wireguard 1.0.20200401.

### CODE REVIEW

**Comment by zx2c4** [comment]
:+1:

**Comment by ColinFinck** [comment]
@akuster Can this be merged?

**Comment by ColinFinck** [comment]
Bump

**Comment by akuster** [comment]
backported to stable/dunfell-nut for testing once current build series is done.

**Comment by ColinFinck** [comment]
https://github.com/openembedded/meta-openembedded/commit/7203130ed8b58c0df75cb72222ac2bcf546bce44 🎉

**Pull request closed without merging**
