### PR TITLE
libcamera: Bumped to latest source revision

### PR DESCRIPTION
**Pull request by madhavank27**
libcamera uses the host machine python instead of sysroot,
We use the patch file for libcamera source to use the
sysroot python. But libcamera team has fix this issue and,
pushed the changes to libcamera source, now we are pointing
to that particular source revision of libcamera.

### CODE REVIEW

**Comment by madhavank27** [comment]
> libcamera uses the host machine python instead of sysroot,
> We use the patch file for libcamera source to use the
> sysroot python. But libcamera team has fix this issue and,
> pushed the changes to libcamera source, now we are pointing
> to that particular source revision of libcamera.

FYI @kraj

**Comment by kraj** [comment]
Fails to build on musl see https://errors.yoctoproject.org/Errors/Details/307979/

```
../git/src/libcamera/include/pipeline_handler.h:91:42: error: 'dev_t' has not been declared
   91 |        std::unique_ptr<CameraData> data, dev_t devnum = 0);
      |                                          ^~~~~

```

perhaps its missing `#include sys/stat.h`

**Comment by madhavank27** [comment]
> Fails to build on musl see https://errors.yoctoproject.org/Errors/Details/307979/
> 
> ```
> ../git/src/libcamera/include/pipeline_handler.h:91:42: error: 'dev_t' has not been declared
>    91 |        std::unique_ptr<CameraData> data, dev_t devnum = 0);
>       |                                          ^~~~~
> ```
> 
> perhaps its missing `#include sys/stat.h`

@kraj 
We could able to reproduce this compilation issue in musl environment.
Also this issue get solved, after including the sys/stat.h header file.
We had now created pull request for libcamera source with this changes

**Comment by madhavank27** [comment]
> > Fails to build on musl see https://errors.yoctoproject.org/Errors/Details/307979/
> > ```
> > ../git/src/libcamera/include/pipeline_handler.h:91:42: error: 'dev_t' has not been declared
> >    91 |        std::unique_ptr<CameraData> data, dev_t devnum = 0);
> >       |                                          ^~~~~
> > ```
> > 
> > 
> > perhaps its missing `#include sys/stat.h`
> 
> @kraj
> We could able to reproduce this compilation issue in musl environment.
> Also this issue get solved, after including the sys/stat.h header file.
> We had now created pull request for libcamera source with this changes

FYI
@kraj we had updated the pull request with the musl compilation issue solved

**Comment by kraj** [comment]
here is next error this time with clang compiler 

https://errors.yoctoproject.org/Errors/Details/390375/

```
src/libcamera/control_serializer.cpp:33:2: error: array designators are a C99 extension [-Werror,-Wc99-designator]
        [ControlTypeNone]       = 1,
        ^~~~~~~~~~~~~~~~~
```

**Comment by madhavank27** [comment]
> here is next error this time with clang compiler
> 
> https://errors.yoctoproject.org/Errors/Details/390375/
> 
> ```
> src/libcamera/control_serializer.cpp:33:2: error: array designators are a C99 extension [-Werror,-Wc99-designator]
>         [ControlTypeNone]       = 1,
>         ^~~~~~~~~~~~~~~~~
> ```

Hi @kraj , I could not able to reproduce this compilation issue with the following setup.
Clang version: 9.0.1
Build: YOE
Machine: qemuX86

Could you please share us the environment details you used, so it could be helpful for us to reproduce this compilation issue.

**Comment by petegriffin** [comment]
@kraj  @madhavank27 I think https://git.linuxtv.org/libcamera.git/commit/?id=461e7ac873cf0def6b3dd6c7905f3c5b65734280 and https://git.linuxtv.org/libcamera.git/commit/?id=a8be6e94e79f602d543a15afd44ef60e378b138f merged upstream should fix these clang compiler warnings

**Comment by madhavank27** [comment]
> @kraj @madhavank27 I think https://git.linuxtv.org/libcamera.git/commit/?id=461e7ac873cf0def6b3dd6c7905f3c5b65734280 and https://git.linuxtv.org/libcamera.git/commit/?id=a8be6e94e79f602d543a15afd44ef60e378b138f merged upstream should fix these clang compiler warnings

@kraj @petegriffin merged upstream fix the compilation issue.
I have updated the pull request with the latest source revision pointing to clang 10 compilation fix.

**Comment by kraj** [comment]
merged with 59daa1229a

**Pull request closed without merging**
