### PR TITLE
kernel-selftest: install kselftest runner

### PR DESCRIPTION
**Pull request by chase-qi**
Install kselftest runner and the required kselftest-list.txt.

Signed-off-by: Chase Qi <chase.qi@linaro.org>

### CODE REVIEW

**Comment by chase-qi** [comment]
Would you please review the change? We are using the runner to run one or more tests in our CI.

**Comment by chase-qi** [comment]
@kraj Thank you for the review. I see it is in the `master` now.

Could you possibly backport the patch to the `kirkstone` and `honister` branches? If not we just have to carry it forward locally until we move to a new release.

**Comment by kraj** [comment]
> @kraj Thank you for the review. I see it is in the `master` now.
> 
> Could you possibly backport the patch to the `kirkstone` and `honister` branches? If not we just have to carry it forward locally until we move to a new release.

@akuster FYI for kirktone

**Comment by akuster** [comment]
I saw the commit in master but had no compelling reason to backport a testing fix to Kirkstone.

I am fine if someone needs it for kirkstone

**Comment by chase-qi** [comment]
> I saw the commit in master but had no compelling reason to backport a testing fix to Kirkstone.
> 
> I am fine if someone needs it for kirkstone

Hi @akuster, thanks for your comment. We need the patch for `Kirkstone` in both [LKFT](https://lkft.linaro.org/) and [Oniro](https://gitlab.eclipse.org/eclipse/oniro-core/oniro) projects as our test definition uses the kselftest runner to run tests in CI. It will make our life easier if you could backport it to `Kirkstone`.  Thanks in advance.

**Comment by akuster** [comment]
Thanks for letting me know. I will take action.

**Comment by chase-qi** [comment]
Closing the PR as it is already cheer picked into kirkstone with https://github.com/openembedded/meta-openembedded/commit/d03e8eecce762f7a39c30b108c083a4e17287de7

**Pull request closed without merging**
