### PR TITLE
avro: add recipe for c++

### PR DESCRIPTION
**Pull request by RuiMarioCosta**
- remove the unittests from the compilation step
- add cmake configuration files to use with find_package

### CODE REVIEW

**Comment by kraj** [comment]
```
ERROR: avro-c++-1.11.3-r0 do_populate_lic: QA Issue: avro-c++: The LIC_FILES_CHKSUM does not match for file://LICENSE;md5=6d502b41f76179fc
84e536236f359cae
avro-c++: The new md5 checksum is 43abf34d8b9908494f83c55d213a7f89
```

**Review by kraj — CHANGES_REQUESTED** [review]
Please fix the license checksum errors.

**Comment by shr-project** [comment]
And add Upstream-Status into the .patch files.

**Comment by kraj** [comment]
compile errors with clang compiler 

```
 | FAILED: CMakeFiles/avrocpp.dir/impl/json/JsonIO.cc.o
    | /home/pokybuild/yocto-worker/meta-oe/build/build/tmp/work/core2-64-poky-linux/avro-c++/1.11.3/recipe-sysroot-native/usr/bin/x86_64-poky-linux/x86_64-poky-linux-g++ --sysr
    | In file included from /home/pokybuild/yocto-worker/meta-oe/build/build/tmp/work/core2-64-poky-linux/avro-c++/1.11.3/recipe-sysroot/usr/include/boost/math/tools/real_cast.
    |                  from /home/pokybuild/yocto-worker/meta-oe/build/build/tmp/work/core2-64-poky-linux/avro-c++/1.11.3/recipe-sysroot/usr/include/boost/math/special_function
    |                  from /home/pokybuild/yocto-worker/meta-oe/build/build/tmp/work/core2-64-poky-linux/avro-c++/1.11.3/git/lang/c++/impl/json/JsonIO.hh:23,
    |                  from /home/pokybuild/yocto-worker/meta-oe/build/build/tmp/work/core2-64-poky-linux/avro-c++/1.11.3/git/lang/c++/impl/json/JsonIO.cc:19:
    | /home/pokybuild/yocto-worker/meta-oe/build/build/tmp/work/core2-64-poky-linux/avro-c++/1.11.3/recipe-sysroot/usr/include/boost/math/tools/config.hpp:23:6: error: #warning
    |    23 | #    warning "The minimum language standard to use Boost.Math will be C++14 starting in July 2023 (Boost 1.82 release)"
    |       |      ^~~~~~~
    | cc1plus: all warnings being treated as errors
 
```

**Comment by kraj** [comment]
and squash commits into a single commit for clean commit history

**Comment by RuiMarioCosta** [comment]
Hello @kraj can you please review again?

**Comment by kraj** [comment]
looks ok. Merged with 1db8a436b3

**Comment by shr-project** [comment]
It fails to build with multilib enabled as it doesn't respect libdir setting

```
ERROR: QA Issue: avro-c++: Files/directories were installed but not shipped in any package:
  /usr/lib/libavrocpp.so
  /usr/lib/libavrocpp.so.1.11.3
  /usr/lib/cmake
  /usr/lib/cmake/avrocpp
  /usr/lib/cmake/avrocpp/AvroCppTargets-release.cmake
  /usr/lib/cmake/avrocpp/AvroCppConfig.cmake
  /usr/lib/cmake/avrocpp/AvroCppTargets.cmake
  /usr/lib/cmake/avrocpp/AvroCppConfigVersion.cmake
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
avro-c++: 8 installed and not shipped files. [installed-vs-shipped]
```

**Comment by shr-project** [comment]
And the HOMEPAGE = "http://apr.apache.org/" also seems copy&paste from apr recipe (instead of https://avro.apache.org/)

**Pull request closed without merging**
